"""
AFT (Account Factory for Terraform) Generator for CARL.

Generates complete AFT Terraform configuration including:
- AFT module configuration
- Account request definitions
- Account customizations (baselines)
- SCPs from compliance framework
- Centralized logging configuration
- Security services delegation
"""

import json
from dataclasses import dataclass, field
from typing import Any, Optional

from services.framework_loader import ComplianceFramework, ServiceControlPolicy


@dataclass
class AFTModuleConfig:
    """Configuration for the AFT module."""
    aft_management_account_email: str
    primary_region: str = "us-east-1"
    additional_regions: list[str] = field(default_factory=list)
    ct_home_region: str = "us-east-1"
    aft_feature_cloudtrail_data_events: bool = False
    aft_feature_enterprise_support: bool = False
    aft_feature_delete_default_vpcs_enabled: bool = True
    terraform_version: str = "1.6.0"
    terraform_distribution: str = "oss"


class AFTGenerator:
    """
    Generates AFT Terraform configurations.

    Creates a complete AFT setup with:
    - Main AFT module (aft-main.tf)
    - Providers (providers.tf)
    - Variables (variables.tf)
    - Account requests (account-requests/*.tf)
    - Account customizations (account-customizations/)
    - Global customizations (global-customizations/)
    - SCPs (scps/)
    """

    def generate_complete_aft(
        self,
        config: AFTModuleConfig,
        framework: ComplianceFramework,
        accounts: list,  # list[AccountConfig]
    ) -> dict[str, str]:
        """
        Generate complete AFT Terraform configuration.

        Returns dict of filename -> content.
        """
        files = {}

        # Core AFT setup
        files["aft-main.tf"] = self._generate_aft_main(config)
        files["providers.tf"] = self._generate_providers(config)
        files["variables.tf"] = self._generate_variables(config)
        files["terraform.tfvars"] = self._generate_tfvars(config)
        files["backend.tf"] = self._generate_backend(config)

        # Account requests
        for account in accounts:
            filename = f"account-requests/{account.name}.tf"
            files[filename] = self._generate_account_request(account, framework)

        # Account customizations
        files["account-customizations/README.md"] = self._generate_customizations_readme()

        # Generate customization for each account type
        customization_types = set()
        for account in accounts:
            customization_types.add(account.ou_name.lower())

        for cust_type in customization_types:
            files[f"account-customizations/{cust_type}/main.tf"] = self._generate_account_customization(
                cust_type, framework, accounts
            )
            files[f"account-customizations/{cust_type}/variables.tf"] = self._generate_customization_variables()

        # Global customizations (applied to ALL accounts)
        files["global-customizations/main.tf"] = self._generate_global_customization(framework)
        files["global-customizations/variables.tf"] = self._generate_customization_variables()

        # SCPs from framework
        for scp in framework.scps:
            filename = f"scps/{scp.name}.tf"
            files[filename] = self._generate_scp_terraform(scp, framework)

        # Security services delegation
        files["security-baseline/security-hub.tf"] = self._generate_security_hub_delegation(framework, accounts)
        files["security-baseline/guardduty.tf"] = self._generate_guardduty_delegation(framework, accounts)
        files["security-baseline/config-aggregator.tf"] = self._generate_config_aggregator(framework, accounts)

        # Centralized logging
        files["logging/cloudtrail-org.tf"] = self._generate_org_cloudtrail(framework)
        files["logging/central-logging-bucket.tf"] = self._generate_central_logging_bucket(framework)

        # VPC modules for workload accounts
        for account in accounts:
            if account.vpcs:
                for vpc in account.vpcs:
                    filename = f"vpcs/{account.name}-{vpc.name}.tf"
                    files[filename] = self._generate_vpc_terraform(account, vpc)

        return files

    def _generate_aft_main(self, config: AFTModuleConfig) -> str:
        """Generate main AFT module configuration."""
        return f'''# AWS Account Factory for Terraform (AFT)
# Generated by CARL - Compliance-driven multi-account setup
#
# This configures AFT to manage account vending with compliance baselines.

module "aft" {{
  source  = "github.com/aws-ia/terraform-aws-control_tower_account_factory"

  # AFT Feature Flags
  aft_feature_cloudtrail_data_events      = {str(config.aft_feature_cloudtrail_data_events).lower()}
  aft_feature_enterprise_support          = {str(config.aft_feature_enterprise_support).lower()}
  aft_feature_delete_default_vpcs_enabled = {str(config.aft_feature_delete_default_vpcs_enabled).lower()}

  # Terraform Configuration
  terraform_version      = "{config.terraform_version}"
  terraform_distribution = "{config.terraform_distribution}"

  # Control Tower Home Region
  ct_home_region = "{config.ct_home_region}"

  # Account IDs (populated after initial setup)
  ct_management_account_id    = var.ct_management_account_id
  log_archive_account_id      = var.log_archive_account_id
  audit_account_id            = var.audit_account_id
  aft_management_account_id   = var.aft_management_account_id

  # VCS Configuration
  vcs_provider                           = "github"
  account_request_repo_name              = var.account_request_repo_name
  global_customizations_repo_name        = var.global_customizations_repo_name
  account_customizations_repo_name       = var.account_customizations_repo_name
  account_provisioning_customizations_repo_name = var.account_provisioning_customizations_repo_name

  # Maximum concurrent account creations
  maximum_concurrent_customizations = 5

  tags = {{
    ManagedBy  = "CARL-AccountFactory"
    Compliance = var.compliance_framework
  }}
}}

# Outputs for use in other configurations
output "aft_account_id" {{
  description = "AFT Management Account ID"
  value       = var.aft_management_account_id
}}

output "aft_codepipeline_name" {{
  description = "Name of the AFT CodePipeline"
  value       = module.aft.aft_codepipeline_name
}}
'''

    def _generate_providers(self, config: AFTModuleConfig) -> str:
        """Generate providers configuration."""
        return f'''# Terraform Providers
# Generated by CARL

terraform {{
  required_version = ">= 1.5.0"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }}
  }}
}}

# Primary region provider
provider "aws" {{
  region = var.primary_region

  default_tags {{
    tags = {{
      ManagedBy   = "CARL-AccountFactory"
      Environment = "management"
    }}
  }}
}}

# US-East-1 provider (required for some global services)
provider "aws" {{
  alias  = "us_east_1"
  region = "us-east-1"
}}
'''

    def _generate_variables(self, config: AFTModuleConfig) -> str:
        """Generate variables file."""
        return '''# Variables for AFT Configuration
# Generated by CARL

variable "ct_management_account_id" {
  description = "Control Tower Management Account ID"
  type        = string
}

variable "log_archive_account_id" {
  description = "Log Archive Account ID"
  type        = string
}

variable "audit_account_id" {
  description = "Audit Account ID"
  type        = string
}

variable "aft_management_account_id" {
  description = "AFT Management Account ID"
  type        = string
}

variable "primary_region" {
  description = "Primary AWS region for deployment"
  type        = string
  default     = "us-east-1"
}

variable "compliance_framework" {
  description = "Compliance framework driving this configuration"
  type        = string
  default     = "SOC2"
}

variable "account_request_repo_name" {
  description = "GitHub repo for account requests"
  type        = string
}

variable "global_customizations_repo_name" {
  description = "GitHub repo for global customizations"
  type        = string
}

variable "account_customizations_repo_name" {
  description = "GitHub repo for account customizations"
  type        = string
}

variable "account_provisioning_customizations_repo_name" {
  description = "GitHub repo for provisioning customizations"
  type        = string
}
'''

    def _generate_tfvars(self, config: AFTModuleConfig) -> str:
        """Generate terraform.tfvars template."""
        return f'''# Terraform Variables
# Generated by CARL - Update these values before applying

# Account IDs (get these from AWS Organizations)
ct_management_account_id  = "REPLACE_WITH_MANAGEMENT_ACCOUNT_ID"
log_archive_account_id    = "REPLACE_WITH_LOG_ARCHIVE_ACCOUNT_ID"
audit_account_id          = "REPLACE_WITH_AUDIT_ACCOUNT_ID"
aft_management_account_id = "REPLACE_WITH_AFT_ACCOUNT_ID"

# Region configuration
primary_region = "{config.primary_region}"

# GitHub repository names (update to match your repos)
account_request_repo_name                      = "your-org/aft-account-requests"
global_customizations_repo_name                = "your-org/aft-global-customizations"
account_customizations_repo_name               = "your-org/aft-account-customizations"
account_provisioning_customizations_repo_name  = "your-org/aft-provisioning-customizations"
'''

    def _generate_backend(self, config: AFTModuleConfig) -> str:
        """Generate backend configuration."""
        return f'''# Terraform Backend Configuration
# Generated by CARL
#
# Configure this to use S3 backend in your AFT management account

terraform {{
  backend "s3" {{
    bucket         = "REPLACE_WITH_TERRAFORM_STATE_BUCKET"
    key            = "aft/terraform.tfstate"
    region         = "{config.primary_region}"
    encrypt        = true
    dynamodb_table = "terraform-state-lock"
  }}
}}
'''

    def _generate_account_request(self, account, framework: ComplianceFramework) -> str:
        """Generate account request Terraform for AFT."""
        tags_str = "\n".join([f'    {k} = "{v}"' for k, v in account.tags.items()])
        if tags_str:
            tags_str = "\n" + tags_str + "\n  "

        # Determine customization name based on OU
        customization_name = account.ou_name.lower()

        return f'''# Account Request: {account.name}
# Generated by CARL for {framework.name} compliance
#
# Purpose: {account.purpose}
# OU: {account.ou_name}

module "account_{account.name.replace("-", "_")}" {{
  source = "./modules/aft-account-request"

  control_tower_parameters = {{
    AccountEmail              = "{account.email or 'REPLACE_WITH_EMAIL'}"
    AccountName               = "{account.name}"
    ManagedOrganizationalUnit = "{account.ou_name}"
    SSOUserEmail              = "{account.sso_user_email or account.email or 'REPLACE_WITH_SSO_EMAIL'}"
    SSOUserFirstName          = "AFT"
    SSOUserLastName           = "Admin"
  }}

  account_tags = {{{tags_str}}}

  change_management_parameters = {{
    change_requested_by = "CARL-AccountFactory"
    change_reason       = "Initial account provisioning for {framework.name} compliance"
  }}

  custom_fields = {{
    compliance_framework = "{framework.id}"
    ou_name              = "{account.ou_name}"
    enable_guardduty     = "{str(account.enable_guardduty).lower()}"
    enable_security_hub  = "{str(account.enable_security_hub).lower()}"
    enable_config        = "{str(account.enable_config).lower()}"
    enable_inspector     = "{str(account.enable_inspector).lower()}"
  }}

  account_customizations_name = "{customization_name}"
}}
'''

    def _generate_customizations_readme(self) -> str:
        """Generate README for account customizations."""
        return '''# Account Customizations

This directory contains account-specific customizations applied by AFT after account creation.

## Structure

Each subdirectory corresponds to an account customization type:
- `security/` - Security account baseline
- `infrastructure/` - Infrastructure account baseline
- `workloads/` - Workload account baseline

## How it works

1. When an account is created via AFT, the `account_customizations_name` field determines which customization to apply
2. AFT runs the Terraform in that customization directory
3. The customization configures the account's security baseline, VPCs, etc.

## Compliance

These customizations are derived from the compliance framework (e.g., SOC2).
Each customization ensures the account meets compliance requirements.
'''

    def _generate_account_customization(
        self,
        customization_type: str,
        framework: ComplianceFramework,
        accounts: list
    ) -> str:
        """Generate account customization Terraform."""
        # Find a representative account of this type
        representative = next(
            (acc for acc in accounts if acc.ou_name.lower() == customization_type),
            None
        )

        guardduty = representative.enable_guardduty if representative else True
        security_hub = representative.enable_security_hub if representative else False
        config = representative.enable_config if representative else True
        inspector = representative.enable_inspector if representative else False

        return f'''# Account Customization: {customization_type}
# Generated by CARL for {framework.name} compliance
#
# Applied to all accounts in the {customization_type.title()} OU

terraform {{
  required_version = ">= 1.5.0"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }}
  }}
}}

# Data sources
data "aws_caller_identity" "current" {{}}
data "aws_region" "current" {{}}

# Local variables
locals {{
  account_id   = data.aws_caller_identity.current.account_id
  region       = data.aws_region.current.name
  compliance   = "{framework.id.upper()}"
  account_type = "{customization_type}"
}}

# =============================================================================
# GuardDuty
# =============================================================================
{"" if not guardduty else '''
resource "aws_guardduty_detector" "main" {
  enable = true

  datasources {
    s3_logs {
      enable = true
    }
    kubernetes {
      audit_logs {
        enable = true
      }
    }
    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          enable = true
        }
      }
    }
  }

  tags = {
    Compliance = local.compliance
    ManagedBy  = "CARL-AccountFactory"
  }
}
'''}

# =============================================================================
# AWS Config
# =============================================================================
{"" if not config else '''
resource "aws_config_configuration_recorder" "main" {
  name     = "default"
  role_arn = aws_iam_role.config.arn

  recording_group {
    all_supported                 = true
    include_global_resource_types = true
  }
}

resource "aws_iam_role" "config" {
  name = "aws-config-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "config.amazonaws.com"
      }
    }]
  })

  tags = {
    Compliance = local.compliance
    ManagedBy  = "CARL-AccountFactory"
  }
}

resource "aws_iam_role_policy_attachment" "config" {
  role       = aws_iam_role.config.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWS_ConfigRole"
}
'''}

# =============================================================================
# Inspector (for workload accounts)
# =============================================================================
{"" if not inspector else '''
resource "aws_inspector2_enabler" "main" {
  account_ids    = [local.account_id]
  resource_types = ["EC2", "ECR", "LAMBDA"]
}
'''}

# =============================================================================
# IAM Password Policy (compliance requirement)
# =============================================================================
resource "aws_iam_account_password_policy" "strict" {{
  minimum_password_length        = 14
  require_uppercase_characters   = true
  require_lowercase_characters   = true
  require_numbers                = true
  require_symbols                = true
  allow_users_to_change_password = true
  max_password_age               = 90
  password_reuse_prevention      = 24
}}

# =============================================================================
# EBS Default Encryption
# =============================================================================
resource "aws_ebs_encryption_by_default" "enabled" {{
  enabled = true
}}

# =============================================================================
# S3 Public Access Block (account level)
# =============================================================================
resource "aws_s3_account_public_access_block" "main" {{
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

# =============================================================================
# Tags
# =============================================================================
output "customization_applied" {{
  value = {{
    account_id   = local.account_id
    account_type = local.account_type
    compliance   = local.compliance
    timestamp    = timestamp()
  }}
}}
'''

    def _generate_customization_variables(self) -> str:
        """Generate variables for account customizations."""
        return '''# Variables for Account Customization
# AFT provides these automatically

variable "account_id" {
  description = "The AWS account ID being customized"
  type        = string
  default     = ""
}

variable "ct_management_account_id" {
  description = "Control Tower management account ID"
  type        = string
  default     = ""
}

variable "log_archive_account_id" {
  description = "Log archive account ID"
  type        = string
  default     = ""
}

variable "audit_account_id" {
  description = "Audit account ID"
  type        = string
  default     = ""
}
'''

    def _generate_global_customization(self, framework: ComplianceFramework) -> str:
        """Generate global customization applied to ALL accounts."""
        return f'''# Global Account Customization
# Generated by CARL for {framework.name} compliance
#
# This is applied to ALL accounts created via AFT

terraform {{
  required_version = ">= 1.5.0"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }}
  }}
}}

data "aws_caller_identity" "current" {{}}

# =============================================================================
# EBS Default Encryption (all accounts)
# =============================================================================
resource "aws_ebs_encryption_by_default" "enabled" {{
  enabled = true
}}

# =============================================================================
# S3 Account-Level Public Access Block (all accounts)
# =============================================================================
resource "aws_s3_account_public_access_block" "main" {{
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

# =============================================================================
# IAM Password Policy (all accounts)
# =============================================================================
resource "aws_iam_account_password_policy" "soc2_compliant" {{
  minimum_password_length        = 14
  require_uppercase_characters   = true
  require_lowercase_characters   = true
  require_numbers                = true
  require_symbols                = true
  allow_users_to_change_password = true
  max_password_age               = 90
  password_reuse_prevention      = 24
}}

# =============================================================================
# Default Security Group Lockdown
# =============================================================================
# Remove all rules from default security group in default VPC
# (AFT should delete default VPCs, but this is defense in depth)

data "aws_vpc" "default" {{
  default = true
}}

resource "aws_default_security_group" "default" {{
  count  = data.aws_vpc.default.id != "" ? 1 : 0
  vpc_id = data.aws_vpc.default.id

  # No ingress or egress rules - locks down the default SG
}}

output "global_customization_applied" {{
  value = {{
    account_id = data.aws_caller_identity.current.account_id
    compliance = "{framework.id.upper()}"
    timestamp  = timestamp()
  }}
}}
'''

    def _generate_scp_terraform(self, scp: ServiceControlPolicy, framework: ComplianceFramework) -> str:
        """Generate SCP Terraform from framework definition."""
        # Convert statement to proper JSON
        if isinstance(scp.statement, list):
            statements = scp.statement
        else:
            statements = [scp.statement]

        policy_document = {
            "Version": "2012-10-17",
            "Statement": statements
        }

        policy_json = json.dumps(policy_document, indent=2)

        target_ous = ", ".join([f'"{ou}"' for ou in scp.target_ous])

        return f'''# Service Control Policy: {scp.name}
# Generated by CARL for {framework.name} compliance
#
# Description: {scp.description}
# Target OUs: {", ".join(scp.target_ous)}

resource "aws_organizations_policy" "{scp.name.lower().replace("-", "_")}" {{
  name        = "{scp.name}"
  description = "{scp.description}"
  type        = "SERVICE_CONTROL_POLICY"

  content = <<POLICY
{policy_json}
POLICY

  tags = {{
    Compliance = "{framework.id.upper()}"
    ManagedBy  = "CARL-AccountFactory"
  }}
}}

# Attach to target OUs
# Note: OU IDs must be provided - update these after organization is created
{"".join([f'''
resource "aws_organizations_policy_attachment" "{scp.name.lower().replace("-", "_")}_{ou.lower().replace("-", "_")}" {{
  policy_id = aws_organizations_policy.{scp.name.lower().replace("-", "_")}.id
  target_id = var.ou_id_{ou.lower().replace("-", "_")}  # Provide OU ID
}}
''' for ou in scp.target_ous])}
'''

    def _generate_security_hub_delegation(self, framework: ComplianceFramework, accounts: list) -> str:
        """Generate Security Hub delegated admin configuration."""
        return f'''# Security Hub Delegated Administrator
# Generated by CARL for {framework.name} compliance
#
# Delegates Security Hub administration to the Security account

resource "aws_securityhub_organization_admin_account" "main" {{
  admin_account_id = var.security_account_id
}}

# Enable Security Hub in the admin account
resource "aws_securityhub_account" "admin" {{
  provider = aws.security_account

  enable_default_standards     = true
  control_finding_generator    = "SECURITY_CONTROL"
  auto_enable_controls         = true
}}

# Enable CIS Benchmark
resource "aws_securityhub_standards_subscription" "cis" {{
  provider      = aws.security_account
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.4.0"
  depends_on    = [aws_securityhub_account.admin]
}}

# Enable AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "aws_fsbp" {{
  provider      = aws.security_account
  standards_arn = "arn:aws:securityhub:${{data.aws_region.current.name}}::standards/aws-foundational-security-best-practices/v/1.0.0"
  depends_on    = [aws_securityhub_account.admin]
}}

# Auto-enable for new member accounts
resource "aws_securityhub_organization_configuration" "main" {{
  provider    = aws.security_account
  auto_enable = true
  depends_on  = [aws_securityhub_organization_admin_account.main]
}}

variable "security_account_id" {{
  description = "Security account ID for delegated admin"
  type        = string
}}

data "aws_region" "current" {{}}
'''

    def _generate_guardduty_delegation(self, framework: ComplianceFramework, accounts: list) -> str:
        """Generate GuardDuty delegated admin configuration."""
        return f'''# GuardDuty Delegated Administrator
# Generated by CARL for {framework.name} compliance
#
# Delegates GuardDuty administration to the Security account

resource "aws_guardduty_organization_admin_account" "main" {{
  admin_account_id = var.security_account_id
}}

# Configure GuardDuty in admin account
resource "aws_guardduty_detector" "admin" {{
  provider = aws.security_account
  enable   = true

  datasources {{
    s3_logs {{
      enable = true
    }}
    kubernetes {{
      audit_logs {{
        enable = true
      }}
    }}
    malware_protection {{
      scan_ec2_instance_with_findings {{
        ebs_volumes {{
          enable = true
        }}
      }}
    }}
  }}

  finding_publishing_frequency = "FIFTEEN_MINUTES"

  tags = {{
    Compliance = "{framework.id.upper()}"
    ManagedBy  = "CARL-AccountFactory"
  }}
}}

# Auto-enable for new member accounts
resource "aws_guardduty_organization_configuration" "main" {{
  provider                         = aws.security_account
  auto_enable_organization_members = "ALL"
  detector_id                      = aws_guardduty_detector.admin.id

  datasources {{
    s3_logs {{
      auto_enable = true
    }}
    kubernetes {{
      audit_logs {{
        enable = true
      }}
    }}
    malware_protection {{
      scan_ec2_instance_with_findings {{
        ebs_volumes {{
          auto_enable = true
        }}
      }}
    }}
  }}

  depends_on = [aws_guardduty_organization_admin_account.main]
}}

variable "security_account_id" {{
  description = "Security account ID for delegated admin"
  type        = string
}}
'''

    def _generate_config_aggregator(self, framework: ComplianceFramework, accounts: list) -> str:
        """Generate AWS Config aggregator configuration."""
        return f'''# AWS Config Aggregator
# Generated by CARL for {framework.name} compliance
#
# Aggregates Config data from all accounts to the Security account

resource "aws_config_configuration_aggregator" "organization" {{
  name = "organization-aggregator"

  organization_aggregation_source {{
    all_regions = true
    role_arn    = aws_iam_role.config_aggregator.arn
  }}

  tags = {{
    Compliance = "{framework.id.upper()}"
    ManagedBy  = "CARL-AccountFactory"
  }}
}}

resource "aws_iam_role" "config_aggregator" {{
  name = "aws-config-aggregator-role"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {{
        Service = "config.amazonaws.com"
      }}
    }}]
  }})

  tags = {{
    Compliance = "{framework.id.upper()}"
    ManagedBy  = "CARL-AccountFactory"
  }}
}}

resource "aws_iam_role_policy_attachment" "config_aggregator" {{
  role       = aws_iam_role.config_aggregator.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSConfigRoleForOrganizations"
}}
'''

    def _generate_org_cloudtrail(self, framework: ComplianceFramework) -> str:
        """Generate organization-level CloudTrail."""
        return f'''# Organization CloudTrail
# Generated by CARL for {framework.name} compliance
#
# Creates an organization trail that logs all accounts

resource "aws_cloudtrail" "organization" {{
  name                          = "organization-trail"
  s3_bucket_name                = var.central_logging_bucket
  s3_key_prefix                 = "cloudtrail"
  include_global_service_events = true
  is_multi_region_trail         = true
  is_organization_trail         = true
  enable_log_file_validation    = true
  kms_key_id                    = var.logging_kms_key_arn

  event_selector {{
    read_write_type           = "All"
    include_management_events = true

    data_resource {{
      type   = "AWS::S3::Object"
      values = ["arn:aws:s3"]
    }}
  }}

  cloud_watch_logs_group_arn = "${{aws_cloudwatch_log_group.cloudtrail.arn}}:*"
  cloud_watch_logs_role_arn  = aws_iam_role.cloudtrail_cloudwatch.arn

  tags = {{
    Compliance = "{framework.id.upper()}"
    ManagedBy  = "CARL-AccountFactory"
  }}
}}

resource "aws_cloudwatch_log_group" "cloudtrail" {{
  name              = "/aws/cloudtrail/organization"
  retention_in_days = 2555  # 7 years for SOC2

  tags = {{
    Compliance = "{framework.id.upper()}"
    ManagedBy  = "CARL-AccountFactory"
  }}
}}

resource "aws_iam_role" "cloudtrail_cloudwatch" {{
  name = "cloudtrail-cloudwatch-role"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {{
        Service = "cloudtrail.amazonaws.com"
      }}
    }}]
  }})
}}

resource "aws_iam_role_policy" "cloudtrail_cloudwatch" {{
  name = "cloudtrail-cloudwatch-policy"
  role = aws_iam_role.cloudtrail_cloudwatch.id

  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Effect = "Allow"
      Action = [
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ]
      Resource = "${{aws_cloudwatch_log_group.cloudtrail.arn}}:*"
    }}]
  }})
}}

variable "central_logging_bucket" {{
  description = "S3 bucket for centralized logging"
  type        = string
}}

variable "logging_kms_key_arn" {{
  description = "KMS key ARN for log encryption"
  type        = string
}}
'''

    def _generate_central_logging_bucket(self, framework: ComplianceFramework) -> str:
        """Generate centralized logging bucket configuration."""
        return f'''# Centralized Logging Bucket
# Generated by CARL for {framework.name} compliance
#
# S3 bucket for organization-wide logs with compliance retention

resource "aws_s3_bucket" "central_logging" {{
  bucket = "central-logging-${{data.aws_caller_identity.current.account_id}}"

  tags = {{
    Compliance = "{framework.id.upper()}"
    ManagedBy  = "CARL-AccountFactory"
    Purpose    = "CentralizedLogging"
  }}
}}

# Versioning (required for compliance)
resource "aws_s3_bucket_versioning" "central_logging" {{
  bucket = aws_s3_bucket.central_logging.id

  versioning_configuration {{
    status = "Enabled"
  }}
}}

# Encryption
resource "aws_s3_bucket_server_side_encryption_configuration" "central_logging" {{
  bucket = aws_s3_bucket.central_logging.id

  rule {{
    apply_server_side_encryption_by_default {{
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.logging.arn
    }}
    bucket_key_enabled = true
  }}
}}

# Public access block
resource "aws_s3_bucket_public_access_block" "central_logging" {{
  bucket = aws_s3_bucket.central_logging.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}}

# Lifecycle - 7 year retention for SOC2
resource "aws_s3_bucket_lifecycle_configuration" "central_logging" {{
  bucket = aws_s3_bucket.central_logging.id

  rule {{
    id     = "compliance-retention"
    status = "Enabled"

    transition {{
      days          = 90
      storage_class = "STANDARD_IA"
    }}

    transition {{
      days          = 365
      storage_class = "GLACIER"
    }}

    expiration {{
      days = 2555  # 7 years
    }}

    noncurrent_version_expiration {{
      noncurrent_days = 90
    }}
  }}
}}

# KMS key for log encryption
resource "aws_kms_key" "logging" {{
  description             = "KMS key for centralized logging encryption"
  enable_key_rotation     = true
  deletion_window_in_days = 30

  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Sid    = "Enable IAM policies"
        Effect = "Allow"
        Principal = {{
          AWS = "arn:aws:iam::${{data.aws_caller_identity.current.account_id}}:root"
        }}
        Action   = "kms:*"
        Resource = "*"
      }},
      {{
        Sid    = "Allow CloudTrail"
        Effect = "Allow"
        Principal = {{
          Service = "cloudtrail.amazonaws.com"
        }}
        Action = [
          "kms:GenerateDataKey*",
          "kms:DescribeKey"
        ]
        Resource = "*"
      }},
      {{
        Sid    = "Allow Config"
        Effect = "Allow"
        Principal = {{
          Service = "config.amazonaws.com"
        }}
        Action = [
          "kms:GenerateDataKey*",
          "kms:Decrypt"
        ]
        Resource = "*"
      }}
    ]
  }})

  tags = {{
    Compliance = "{framework.id.upper()}"
    ManagedBy  = "CARL-AccountFactory"
  }}
}}

resource "aws_kms_alias" "logging" {{
  name          = "alias/central-logging"
  target_key_id = aws_kms_key.logging.key_id
}}

# Bucket policy for organization access
resource "aws_s3_bucket_policy" "central_logging" {{
  bucket = aws_s3_bucket.central_logging.id

  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Sid    = "AllowCloudTrail"
        Effect = "Allow"
        Principal = {{
          Service = "cloudtrail.amazonaws.com"
        }}
        Action   = "s3:GetBucketAcl"
        Resource = aws_s3_bucket.central_logging.arn
      }},
      {{
        Sid    = "AllowCloudTrailWrite"
        Effect = "Allow"
        Principal = {{
          Service = "cloudtrail.amazonaws.com"
        }}
        Action   = "s3:PutObject"
        Resource = "${{aws_s3_bucket.central_logging.arn}}/*"
        Condition = {{
          StringEquals = {{
            "s3:x-amz-acl" = "bucket-owner-full-control"
          }}
        }}
      }},
      {{
        Sid    = "AllowConfig"
        Effect = "Allow"
        Principal = {{
          Service = "config.amazonaws.com"
        }}
        Action = [
          "s3:GetBucketAcl",
          "s3:ListBucket"
        ]
        Resource = aws_s3_bucket.central_logging.arn
      }},
      {{
        Sid    = "AllowConfigWrite"
        Effect = "Allow"
        Principal = {{
          Service = "config.amazonaws.com"
        }}
        Action   = "s3:PutObject"
        Resource = "${{aws_s3_bucket.central_logging.arn}}/*"
        Condition = {{
          StringEquals = {{
            "s3:x-amz-acl" = "bucket-owner-full-control"
          }}
        }}
      }}
    ]
  }})
}}

data "aws_caller_identity" "current" {{}}

output "logging_bucket_name" {{
  value = aws_s3_bucket.central_logging.id
}}

output "logging_bucket_arn" {{
  value = aws_s3_bucket.central_logging.arn
}}

output "logging_kms_key_arn" {{
  value = aws_kms_key.logging.arn
}}
'''

    def _generate_vpc_terraform(self, account, vpc) -> str:
        """Generate VPC Terraform for a workload account."""
        return f'''# VPC: {vpc.name} for {account.name}
# Generated by CARL
#
# Environment: {vpc.environment}
# CIDR: {vpc.cidr}
# AZs: {vpc.availability_zones}

locals {{
  vpc_name = "{vpc.name}"
  vpc_cidr = "{vpc.cidr}"
  azs      = {vpc.availability_zones}
}}

module "vpc_{vpc.name.replace("-", "_")}" {{
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = local.vpc_name
  cidr = local.vpc_cidr

  azs             = slice(data.aws_availability_zones.available.names, 0, local.azs)
  private_subnets = [for i in range(local.azs) : cidrsubnet(local.vpc_cidr, 4, i)]
  public_subnets  = [for i in range(local.azs) : cidrsubnet(local.vpc_cidr, 4, i + local.azs)]

  enable_nat_gateway     = {str(vpc.enable_nat_gateway).lower()}
  single_nat_gateway     = {str(vpc.availability_zones == 1).lower()}
  one_nat_gateway_per_az = {str(vpc.availability_zones > 1 and vpc.enable_nat_gateway).lower()}

  enable_dns_hostnames = true
  enable_dns_support   = true

  # VPC Flow Logs
  enable_flow_log                      = true
  create_flow_log_cloudwatch_log_group = true
  create_flow_log_cloudwatch_iam_role  = true
  flow_log_max_aggregation_interval    = 60

  tags = {{
    Environment = "{vpc.environment}"
    Account     = "{account.name}"
    ManagedBy   = "CARL-AccountFactory"
  }}

  vpc_tags = {{
    Name = local.vpc_name
  }}
}}

{"" if not vpc.enable_vpc_endpoints else f'''
# VPC Endpoints for private access to AWS services
module "vpc_endpoints_{vpc.name.replace("-", "_")}" {{
  source  = "terraform-aws-modules/vpc/aws//modules/vpc-endpoints"
  version = "~> 5.0"

  vpc_id = module.vpc_{vpc.name.replace("-", "_")}.vpc_id

  endpoints = {{
    s3 = {{
      service         = "s3"
      service_type    = "Gateway"
      route_table_ids = module.vpc_{vpc.name.replace("-", "_")}.private_route_table_ids
    }}
    ssm = {{
      service             = "ssm"
      private_dns_enabled = true
      subnet_ids          = module.vpc_{vpc.name.replace("-", "_")}.private_subnets
    }}
    ssmmessages = {{
      service             = "ssmmessages"
      private_dns_enabled = true
      subnet_ids          = module.vpc_{vpc.name.replace("-", "_")}.private_subnets
    }}
    ec2messages = {{
      service             = "ec2messages"
      private_dns_enabled = true
      subnet_ids          = module.vpc_{vpc.name.replace("-", "_")}.private_subnets
    }}
  }}

  tags = {{
    Environment = "{vpc.environment}"
    ManagedBy   = "CARL-AccountFactory"
  }}
}}
'''}

data "aws_availability_zones" "available" {{
  state = "available"
}}

output "vpc_{vpc.name.replace("-", "_")}_id" {{
  value = module.vpc_{vpc.name.replace("-", "_")}.vpc_id
}}

output "vpc_{vpc.name.replace("-", "_")}_private_subnets" {{
  value = module.vpc_{vpc.name.replace("-", "_")}.private_subnets
}}

output "vpc_{vpc.name.replace("-", "_")}_public_subnets" {{
  value = module.vpc_{vpc.name.replace("-", "_")}.public_subnets
}}
'''
