"""Orchestrates Terraform code upload to GitHub and Slack."""
import json
import re
from datetime import datetime
from typing import Any
from services.github_service import GitHubService
from services.slack_service import SlackService


class CodeUploader:
    """Handles uploading generated Terraform code to GitHub and posting to Slack."""

    def __init__(self, github: GitHubService, slack: SlackService):
        self.github = github
        self.slack = slack

    def upload_and_notify(
        self,
        channel_id: str,
        user_id: str,
        blueprint_name: str,
        terraform_code: str,
        metadata: dict[str, Any]
    ) -> dict:
        """
        Complete upload flow:
        1. Create GitHub branch
        2. Commit Terraform files
        3. Create Pull Request
        4. Post summary to Slack channel
        5. Post code to thread
        6. Upload file to Slack

        Returns dict with GitHub and Slack info.
        """
        timestamp = datetime.now().strftime("%Y%m%d-%H%M")
        blueprint_short = blueprint_name.replace("/", "-")

        # 1. Create branch (uses default branch, initializes repo if empty)
        branch_name = f"feature/u{user_id}-{blueprint_short}-{timestamp}"
        self.github.create_branch(branch_name, base_branch=None)

        # 2. Prepare files
        deployment_path = f"deployments/users/{user_id}/{blueprint_short}/{timestamp}"
        files = {
            f"{deployment_path}/main.tf": terraform_code,
            f"{deployment_path}/backend.tf": self._generate_backend_config(deployment_path),
            f"{deployment_path}/metadata.json": json.dumps(metadata, indent=2)
        }

        # 3. Commit files
        commit_message = self._format_commit_message(user_id, blueprint_name, metadata)
        commit_sha = self.github.commit_files(branch_name, files, commit_message)

        # 4. Create PR (target default branch)
        pr_title = f"Deploy {blueprint_name}"
        pr_body = self._format_pr_body(blueprint_name, metadata)
        base_branch = self.github.get_default_branch()
        pr = self.github.create_pull_request(pr_title, pr_body, branch_name, base=base_branch)

        # 5. Post to Slack channel (summary)
        summary_msg = self.slack.post_message(
            channel_id,
            blocks=self._build_summary_blocks(blueprint_name, pr, metadata)
        )

        # 6. Post code to thread (adaptive: full for small, summary for large)
        thread_ts = summary_msg.get("ts")
        self._post_code_to_thread(channel_id, thread_ts, terraform_code, blueprint_name, metadata)

        # 7. Upload file (optional - if this fails, we still succeed)
        try:
            self.slack.upload_file(
                channels=[channel_id],
                content=terraform_code,
                filename=f"{blueprint_short}_{timestamp}.tf",
                title=f"Terraform: {blueprint_name}",
                initial_comment=f"Full code for PR #{pr['number']}: {pr['html_url']}"
            )
        except Exception as e:
            # Log error but don't fail the whole operation
            # Code is still in GitHub PR and Slack thread
            logger = __import__('utils.logger', fromlist=['get_logger']).get_logger(__name__)
            logger.warning(f"Failed to upload file to Slack: {e}")

        return {
            "branch": branch_name,
            "commit_sha": commit_sha,
            "pr_number": pr["number"],
            "pr_url": pr["html_url"],
            "slack_ts": thread_ts
        }

    def _generate_backend_config(self, deployment_path: str) -> str:
        """Generate S3 backend configuration."""
        return f"""terraform {{
  backend "s3" {{
    bucket         = "carl-tfstate-${{data.aws_caller_identity.current.account_id}}"
    key            = "{deployment_path}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "carl-tfstate-locks"
  }}
}}
"""

    def _format_commit_message(self, user_id: str, blueprint: str, metadata: dict) -> str:
        """Format commit message."""
        return f"""feat(infra): {blueprint}

Generated by: CARL Infrastructure Builder
User: {user_id}
Blueprint: {blueprint}
Timestamp: {datetime.now().isoformat()}

Compliance: {', '.join(metadata.get('compliance_notes', [])[:3])}

Co-Authored-By: CARL Bot <noreply@carl.ai>
"""

    def _format_pr_body(self, blueprint: str, metadata: dict) -> str:
        """Format PR description."""
        notes = metadata.get('compliance_notes', [])
        return f"""## Infrastructure Deployment: {blueprint}

### Generated by CARL

**Compliance Notes:**
{chr(10).join([f'- {n}' for n in notes[:5]])}

### Next Steps

1. Review the Terraform code in this PR
2. GitHub Actions will validate and generate a plan
3. Review the plan output
4. Merge this PR to deploy to dev
5. Run `apply-dev` workflow manually to apply changes

---
🤖 Generated by [CARL Infrastructure Builder](https://github.com/your-org/CARL)
"""

    def _build_summary_blocks(self, blueprint: str, pr: dict, metadata: dict) -> list[dict]:
        """Build Slack blocks for summary message."""
        return [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": f"✅ Infrastructure Code Generated"}
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Blueprint:*\n{blueprint}"},
                    {"type": "mrkdwn", "text": f"*Pull Request:*\n<{pr['html_url']}|#{pr['number']}>"}
                ]
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*🔐 Compliance Notes:*\n" + "\n".join([f"• {n}" for n in metadata.get('compliance_notes', [])[:3]])
                }
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*📋 Next Steps:*\n1. Review code in GitHub PR\n2. GitHub Actions will validate and plan\n3. Review plan output\n4. Merge PR and run apply workflow"
                }
            },
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "📂 View Pull Request"},
                        "url": pr["html_url"],
                        "style": "primary"
                    },
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "📄 View Code"},
                        "url": f"{pr['html_url']}/files"
                    }
                ]
            },
            {
                "type": "context",
                "elements": [
                    {"type": "mrkdwn", "text": "ℹ️ Code details in thread, full code attached as file. Review in GitHub before deployment."}
                ]
            }
        ]

    def _post_code_to_thread(self, channel: str, thread_ts: str, code: str, blueprint: str, metadata: dict):
        """Post code to thread - adaptive based on size."""
        code_length = len(code)
        small_code_threshold = 3000  # Slack block limit is ~3000 chars

        if code_length <= small_code_threshold:
            # Small code: Show full code
            self.slack.post_message(
                channel,
                thread_ts=thread_ts,
                blocks=[
                    {"type": "section", "text": {"type": "mrkdwn", "text": f"*📄 Complete Terraform Code*\n({code_length} chars)"}},
                    {"type": "section", "text": {"type": "mrkdwn", "text": f"```terraform\n{code}\n```"}}
                ]
            )
        else:
            # Large code: Generate and show summary instead
            summary = self._generate_code_summary(code, blueprint, metadata)
            self.slack.post_message(
                channel,
                thread_ts=thread_ts,
                blocks=[
                    {"type": "section", "text": {"type": "mrkdwn", "text": f"*📊 Code Summary*\n(Full code: {code_length} chars - see file attachment or GitHub)"}},
                    {"type": "section", "text": {"type": "mrkdwn", "text": summary}}
                ]
            )

    def _generate_code_summary(self, code: str, blueprint: str, metadata: dict) -> str:
        """Generate a summary of large Terraform code."""
        # Count resources by type
        resource_pattern = r'resource\s+"([^"]+)"\s+"([^"]+)"'
        resources = re.findall(resource_pattern, code)
        resource_counts = {}
        for resource_type, resource_name in resources:
            resource_counts[resource_type] = resource_counts.get(resource_type, 0) + 1

        # Count data sources
        data_pattern = r'data\s+"([^"]+)"\s+"([^"]+)"'
        data_sources = re.findall(data_pattern, code)
        data_count = len(data_sources)

        # Count modules
        module_pattern = r'module\s+"([^"]+)"'
        modules = re.findall(module_pattern, code)
        module_count = len(modules)

        # Count variables
        variable_pattern = r'variable\s+"([^"]+)"'
        variables = re.findall(variable_pattern, code)
        var_count = len(variables)

        # Count outputs
        output_pattern = r'output\s+"([^"]+)"'
        outputs = re.findall(output_pattern, code)
        output_count = len(outputs)

        # Build summary
        summary_parts = [
            f"*Blueprint:* `{blueprint}`",
            "",
            "*📦 Resources:*"
        ]

        if resource_counts:
            for resource_type, count in sorted(resource_counts.items()):
                summary_parts.append(f"  • `{resource_type}` × {count}")
        else:
            summary_parts.append("  • No resources defined")

        summary_parts.append("")
        summary_parts.append("*📊 Components:*")
        summary_parts.append(f"  • Data Sources: {data_count}")
        summary_parts.append(f"  • Modules: {module_count}")
        summary_parts.append(f"  • Variables: {var_count}")
        summary_parts.append(f"  • Outputs: {output_count}")

        # Add compliance notes if available
        compliance_notes = metadata.get('compliance_notes', [])
        if compliance_notes:
            summary_parts.append("")
            summary_parts.append("*🔐 Compliance:*")
            for note in compliance_notes[:3]:
                summary_parts.append(f"  • {note}")

        summary_parts.append("")
        summary_parts.append("_→ Download file attachment or view in GitHub PR for full code_")

        return "\n".join(summary_parts)
