"""
Terraform Code Generator for CARL.

Generates Terraform modules and configurations for bootstrap components:
- AWS Organizations (OUs, SCPs)
- IAM Identity Center (permission sets, groups, assignments)
- Security services (GuardDuty, Security Hub, Inspector, Config)
- VPC Endpoints
- KMS keys
- Account baselines
"""

import logging
from dataclasses import dataclass
from typing import List, Dict, Any, Optional
import json

logger = logging.getLogger(__name__)


@dataclass
class TerraformModule:
    """Represents a generated Terraform module."""

    name: str
    path: str
    content: str
    description: str


class TerraformGenerator:
    """Service for generating Terraform code from CARL configurations."""

    def __init__(self):
        self.generated_modules: List[TerraformModule] = []

    def generate_organizations_module(
        self,
        ou_structure: List[Dict[str, Any]],
        scps: List[Dict[str, Any]]
    ) -> str:
        """
        Generate Terraform module for AWS Organizations.

        Args:
            ou_structure: List of OU configurations
            scps: List of SCP configurations

        Returns:
            Terraform HCL code as string
        """
        terraform = []

        # Header
        terraform.append("""# AWS Organizations Module
# Generated by CARL

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
""")

        # OUs
        terraform.append("# Organizational Units\n")
        for idx, ou in enumerate(ou_structure):
            ou_resource_name = ou["name"].lower().replace(" ", "_").replace("-", "_")

            terraform.append(f"""resource "aws_organizations_organizational_unit" "{ou_resource_name}" {{
  name      = "{ou["name"]}"
  parent_id = {self._get_parent_reference(ou, idx)}

  tags = {{
    Name        = "{ou["name"]}"
    Description = "{ou.get('description', ou['name'])}"
    ManagedBy   = "CARL"
  }}
}}
""")

        # SCPs
        terraform.append("\n# Service Control Policies\n")
        for scp in scps:
            scp_resource_name = scp["name"].lower().replace(" ", "_").replace("-", "_")

            # Convert policy dict to JSON string
            policy_json = json.dumps(scp["policy"], indent=2)

            terraform.append(f"""resource "aws_organizations_policy" "{scp_resource_name}" {{
  name        = "{scp["name"]}"
  description = "{scp.get('description', scp['name'])}"
  type        = "SERVICE_CONTROL_POLICY"

  content = <<POLICY
{policy_json}
POLICY

  tags = {{
    Name      = "{scp["name"]}"
    ManagedBy = "CARL"
  }}
}}
""")

            # SCP attachments
            if "target_ous" in scp:
                for target_ou in scp["target_ous"]:
                    target_resource_name = target_ou.lower().replace(" ", "_").replace("-", "_")
                    terraform.append(f"""
resource "aws_organizations_policy_attachment" "{scp_resource_name}_{target_resource_name}" {{
  policy_id = aws_organizations_policy.{scp_resource_name}.id
  target_id = aws_organizations_organizational_unit.{target_resource_name}.id
}}
""")

        # Outputs
        terraform.append("\n# Outputs\n")
        for ou in ou_structure:
            ou_resource_name = ou["name"].lower().replace(" ", "_").replace("-", "_")
            terraform.append(f"""output "{ou_resource_name}_id" {{
  description = "ID of {ou['name']} OU"
  value       = aws_organizations_organizational_unit.{ou_resource_name}.id
}}
""")

        return "\n".join(terraform)

    def generate_identity_center_module(
        self,
        permission_sets: List[Dict[str, Any]],
        groups: List[Dict[str, Any]],
        assignments: Optional[List[Dict[str, Any]]] = None
    ) -> str:
        """
        Generate Terraform module for IAM Identity Center.

        Args:
            permission_sets: List of permission set configurations
            groups: List of group configurations
            assignments: List of account assignment configurations

        Returns:
            Terraform HCL code as string
        """
        terraform = []

        # Header
        terraform.append("""# IAM Identity Center Module
# Generated by CARL

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Data source for Identity Center instance
data "aws_ssoadmin_instances" "main" {}

locals {
  instance_arn = tolist(data.aws_ssoadmin_instances.main.arns)[0]
  identity_store_id = tolist(data.aws_ssoadmin_instances.main.identity_store_ids)[0]
}
""")

        # Permission Sets
        terraform.append("\n# Permission Sets\n")
        for ps in permission_sets:
            ps_resource_name = ps["name"].lower().replace(" ", "_").replace("-", "_")

            terraform.append(f"""resource "aws_ssoadmin_permission_set" "{ps_resource_name}" {{
  name             = "{ps["name"]}"
  description      = "{ps.get('description', ps['name'])}"
  instance_arn     = local.instance_arn
  session_duration = "{ps.get('session_duration', 'PT1H')}"

  tags = {{
    Name      = "{ps["name"]}"
    ManagedBy = "CARL"
  }}
}}
""")

            # Managed policies
            if "managed_policies" in ps:
                for policy_arn in ps["managed_policies"]:
                    policy_name = policy_arn.split("/")[-1].lower().replace("-", "_")
                    terraform.append(f"""
resource "aws_ssoadmin_managed_policy_attachment" "{ps_resource_name}_{policy_name}" {{
  instance_arn       = local.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.{ps_resource_name}.arn
  managed_policy_arn = "{policy_arn}"
}}
""")

            # Custom inline policy
            if "inline_policy" in ps:
                policy_json = json.dumps(ps["inline_policy"], indent=2)
                terraform.append(f"""
resource "aws_ssoadmin_permission_set_inline_policy" "{ps_resource_name}_inline" {{
  instance_arn       = local.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.{ps_resource_name}.arn

  inline_policy = <<POLICY
{policy_json}
POLICY
}}
""")

        # Groups
        terraform.append("\n# Groups\n")
        for group in groups:
            group_resource_name = group["name"].lower().replace(" ", "_").replace("-", "_")

            terraform.append(f"""resource "aws_identitystore_group" "{group_resource_name}" {{
  display_name      = "{group["name"]}"
  description       = "{group.get('description', group['name'])}"
  identity_store_id = local.identity_store_id
}}
""")

        # Account Assignments
        if assignments:
            terraform.append("\n# Account Assignments\n")
            for idx, assignment in enumerate(assignments):
                ps_name = assignment["permission_set_name"].lower().replace(" ", "_").replace("-", "_")
                group_name = assignment["principal_name"].lower().replace(" ", "_").replace("-", "_")
                account_id = assignment["account_id"]

                terraform.append(f"""resource "aws_ssoadmin_account_assignment" "assignment_{idx}" {{
  instance_arn       = local.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.{ps_name}.arn
  principal_type     = "{assignment.get('principal_type', 'GROUP')}"
  principal_id       = aws_identitystore_group.{group_name}.group_id
  target_type        = "AWS_ACCOUNT"
  target_id          = "{account_id}"
}}
""")

        # Outputs
        terraform.append("\n# Outputs\n")
        for ps in permission_sets:
            ps_resource_name = ps["name"].lower().replace(" ", "_").replace("-", "_")
            terraform.append(f"""output "{ps_resource_name}_arn" {{
  description = "ARN of {ps['name']} permission set"
  value       = aws_ssoadmin_permission_set.{ps_resource_name}.arn
}}
""")

        return "\n".join(terraform)

    def generate_security_services_module(
        self,
        delegated_admin_account_id: str,
        regions: List[str],
        enable_security_hub: bool = True,
        enable_guardduty: bool = True,
        enable_inspector: bool = True
    ) -> str:
        """
        Generate Terraform module for security services.

        Args:
            delegated_admin_account_id: Account ID for delegated admin
            regions: List of regions to enable services
            enable_security_hub: Whether to enable Security Hub
            enable_guardduty: Whether to enable GuardDuty
            enable_inspector: Whether to enable Inspector

        Returns:
            Terraform HCL code as string
        """
        terraform = []

        # Header
        terraform.append(f"""# Security Services Module
# Generated by CARL

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

variable "delegated_admin_account_id" {{
  description = "Account ID for delegated administrator"
  type        = string
  default     = "{delegated_admin_account_id}"
}}
""")

        # Provider aliases for multi-region
        terraform.append("\n# Provider aliases for multi-region deployment\n")
        for region in regions:
            region_alias = region.replace("-", "_")
            terraform.append(f"""provider "aws" {{
  alias  = "{region_alias}"
  region = "{region}"
}}
""")

        # GuardDuty
        if enable_guardduty:
            terraform.append("\n# GuardDuty\n")
            for region in regions:
                region_alias = region.replace("-", "_")
                terraform.append(f"""
resource "aws_guardduty_detector" "main_{region_alias}" {{
  provider = aws.{region_alias}
  enable   = true

  finding_publishing_frequency = "FIFTEEN_MINUTES"

  datasources {{
    s3_logs {{
      enable = true
    }}
    kubernetes {{
      audit_logs {{
        enable = true
      }}
    }}
  }}

  tags = {{
    Name      = "guardduty-{region}"
    ManagedBy = "CARL"
  }}
}}

resource "aws_guardduty_organization_admin_account" "main_{region_alias}" {{
  provider         = aws.{region_alias}
  admin_account_id = var.delegated_admin_account_id
  depends_on       = [aws_guardduty_detector.main_{region_alias}]
}}

resource "aws_guardduty_organization_configuration" "main_{region_alias}" {{
  provider    = aws.{region_alias}
  auto_enable = true
  detector_id = aws_guardduty_detector.main_{region_alias}.id

  datasources {{
    s3_logs {{
      auto_enable = true
    }}
    kubernetes {{
      audit_logs {{
        enable = true
      }}
    }}
  }}

  depends_on = [aws_guardduty_organization_admin_account.main_{region_alias}]
}}
""")

        # Security Hub
        if enable_security_hub:
            terraform.append("\n# Security Hub\n")
            for region in regions:
                region_alias = region.replace("-", "_")
                terraform.append(f"""
resource "aws_securityhub_account" "main_{region_alias}" {{
  provider = aws.{region_alias}
}}

resource "aws_securityhub_organization_admin_account" "main_{region_alias}" {{
  provider         = aws.{region_alias}
  admin_account_id = var.delegated_admin_account_id
  depends_on       = [aws_securityhub_account.main_{region_alias}]
}}

resource "aws_securityhub_organization_configuration" "main_{region_alias}" {{
  provider    = aws.{region_alias}
  auto_enable = true
  depends_on  = [aws_securityhub_organization_admin_account.main_{region_alias}]
}}

# Enable CIS AWS Foundations Benchmark
resource "aws_securityhub_standards_subscription" "cis_{region_alias}" {{
  provider      = aws.{region_alias}
  standards_arn = "arn:aws:securityhub:{region}::standards/cis-aws-foundations-benchmark/v/1.4.0"
  depends_on    = [aws_securityhub_account.main_{region_alias}]
}}
""")

        # Inspector
        if enable_inspector:
            terraform.append("\n# Inspector v2\n")
            for region in regions:
                region_alias = region.replace("-", "_")
                terraform.append(f"""
resource "aws_inspector2_enabler" "main_{region_alias}" {{
  provider       = aws.{region_alias}
  account_ids    = [var.delegated_admin_account_id]
  resource_types = ["EC2", "ECR", "LAMBDA"]
}}

resource "aws_inspector2_delegated_admin_account" "main_{region_alias}" {{
  provider   = aws.{region_alias}
  account_id = var.delegated_admin_account_id
  depends_on = [aws_inspector2_enabler.main_{region_alias}]
}}

resource "aws_inspector2_organization_configuration" "main_{region_alias}" {{
  provider = aws.{region_alias}

  auto_enable {{
    ec2    = true
    ecr    = true
    lambda = true
  }}

  depends_on = [aws_inspector2_delegated_admin_account.main_{region_alias}]
}}
""")

        # Outputs
        terraform.append("\n# Outputs\n")
        if enable_guardduty:
            for region in regions:
                region_alias = region.replace("-", "_")
                terraform.append(f"""output "guardduty_detector_id_{region_alias}" {{
  description = "GuardDuty detector ID in {region}"
  value       = aws_guardduty_detector.main_{region_alias}.id
}}
""")

        return "\n".join(terraform)

    def generate_vpc_endpoints_module(
        self,
        vpc_id: str,
        subnet_ids: List[str],
        endpoints: List[str]
    ) -> str:
        """
        Generate Terraform module for VPC endpoints.

        Args:
            vpc_id: VPC ID where endpoints will be created
            subnet_ids: List of subnet IDs for interface endpoints
            endpoints: List of endpoint service names (e.g., ["s3", "dynamodb", "ec2"])

        Returns:
            Terraform HCL code as string
        """
        terraform = []

        # Header
        terraform.append(f"""# VPC Endpoints Module
# Generated by CARL

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

variable "vpc_id" {{
  description = "VPC ID for endpoints"
  type        = string
  default     = "{vpc_id}"
}}

variable "subnet_ids" {{
  description = "Subnet IDs for interface endpoints"
  type        = list(string)
  default     = {json.dumps(subnet_ids)}
}}

data "aws_region" "current" {{}}
""")

        # Gateway endpoints (S3, DynamoDB)
        gateway_endpoints = [e for e in endpoints if e in ["s3", "dynamodb"]]
        if gateway_endpoints:
            terraform.append("\n# Gateway Endpoints\n")
            for endpoint in gateway_endpoints:
                terraform.append(f"""resource "aws_vpc_endpoint" "{endpoint}" {{
  vpc_id            = var.vpc_id
  service_name      = "com.amazonaws.${{data.aws_region.current.name}}.{endpoint}"
  vpc_endpoint_type = "Gateway"

  tags = {{
    Name      = "{endpoint}-gateway-endpoint"
    ManagedBy = "CARL"
  }}
}}
""")

        # Interface endpoints
        interface_endpoints = [e for e in endpoints if e not in ["s3", "dynamodb"]]
        if interface_endpoints:
            terraform.append("\n# Security Group for Interface Endpoints\n")
            terraform.append("""resource "aws_security_group" "vpc_endpoints" {
  name_description = "Security group for VPC endpoints"
  vpc_id          = var.vpc_id

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = [data.aws_vpc.main.cidr_block]
    description = "HTTPS from VPC"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound"
  }

  tags = {
    Name      = "vpc-endpoints-sg"
    ManagedBy = "CARL"
  }
}

data "aws_vpc" "main" {
  id = var.vpc_id
}
""")

            terraform.append("\n# Interface Endpoints\n")
            for endpoint in interface_endpoints:
                terraform.append(f"""resource "aws_vpc_endpoint" "{endpoint}" {{
  vpc_id              = var.vpc_id
  service_name        = "com.amazonaws.${{data.aws_region.current.name}}.{endpoint}"
  vpc_endpoint_type   = "Interface"
  subnet_ids          = var.subnet_ids
  security_group_ids  = [aws_security_group.vpc_endpoints.id]
  private_dns_enabled = true

  tags = {{
    Name      = "{endpoint}-interface-endpoint"
    ManagedBy = "CARL"
  }}
}}
""")

        # Outputs
        terraform.append("\n# Outputs\n")
        for endpoint in endpoints:
            terraform.append(f"""output "{endpoint}_endpoint_id" {{
  description = "ID of {endpoint} VPC endpoint"
  value       = aws_vpc_endpoint.{endpoint}.id
}}
""")

        return "\n".join(terraform)

    def generate_kms_keys_module(
        self,
        keys: List[Dict[str, Any]]
    ) -> str:
        """
        Generate Terraform module for KMS keys.

        Args:
            keys: List of KMS key configurations

        Returns:
            Terraform HCL code as string
        """
        terraform = []

        # Header
        terraform.append("""# KMS Keys Module
# Generated by CARL

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}
""")

        # KMS Keys
        terraform.append("\n# KMS Keys\n")
        for key in keys:
            key_resource_name = key["alias"].replace("/", "_").replace("-", "_")

            terraform.append(f"""resource "aws_kms_key" "{key_resource_name}" {{
  description             = "{key.get('description', key['alias'])}"
  deletion_window_in_days = {key.get('deletion_window_days', 30)}
  enable_key_rotation     = {str(key.get('enable_rotation', True)).lower()}

  tags = {{
    Name      = "{key['alias']}"
    Purpose   = "{key.get('purpose', 'encryption')}"
    ManagedBy = "CARL"
  }}
}}

resource "aws_kms_alias" "{key_resource_name}_alias" {{
  name          = "alias/{key['alias']}"
  target_key_id = aws_kms_key.{key_resource_name}.key_id
}}
""")

        # Outputs
        terraform.append("\n# Outputs\n")
        for key in keys:
            key_resource_name = key["alias"].replace("/", "_").replace("-", "_")
            terraform.append(f"""output "{key_resource_name}_id" {{
  description = "ID of {key['alias']} KMS key"
  value       = aws_kms_key.{key_resource_name}.id
}}

output "{key_resource_name}_arn" {{
  description = "ARN of {key['alias']} KMS key"
  value       = aws_kms_key.{key_resource_name}.arn
}}
""")

        return "\n".join(terraform)

    def _get_parent_reference(self, ou: Dict[str, Any], idx: int) -> str:
        """Get parent reference for OU."""
        if "parent_id" in ou:
            return f'"{ou["parent_id"]}"'
        elif idx == 0:
            return 'data.aws_organizations_organization.main.roots[0].id'
        else:
            # Assume parent is root for simplicity
            return 'data.aws_organizations_organization.main.roots[0].id'

    def generate_complete_environment(
        self,
        org_config: Dict[str, Any],
        identity_config: Dict[str, Any],
        security_config: Dict[str, Any]
    ) -> Dict[str, str]:
        """
        Generate complete Terraform configuration for bootstrapped environment.

        Args:
            org_config: Organizations configuration
            identity_config: Identity Center configuration
            security_config: Security services configuration

        Returns:
            Dictionary of module names to Terraform code
        """
        modules = {}

        # Generate each module
        modules["organizations"] = self.generate_organizations_module(
            org_config.get("ou_structure", []),
            org_config.get("scps", [])
        )

        modules["identity_center"] = self.generate_identity_center_module(
            identity_config.get("permission_sets", []),
            identity_config.get("groups", []),
            identity_config.get("assignments")
        )

        modules["security_services"] = self.generate_security_services_module(
            security_config["delegated_admin_account_id"],
            security_config.get("regions", ["us-east-1"]),
            security_config.get("enable_security_hub", True),
            security_config.get("enable_guardduty", True),
            security_config.get("enable_inspector", True)
        )

        # Generate root module that ties everything together
        modules["main"] = self._generate_root_module(modules.keys())

        return modules

    def _generate_root_module(self, submodules: List[str]) -> str:
        """Generate root Terraform module that references submodules."""
        terraform = []

        terraform.append("""# Root Terraform Module
# Generated by CARL
# This module orchestrates all bootstrap components

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Uncomment for remote state
  # backend "s3" {
  #   bucket = "your-terraform-state-bucket"
  #   key    = "carl-bootstrap/terraform.tfstate"
  #   region = "us-east-1"
  # }
}

provider "aws" {
  region = "us-east-1"
}
""")

        # Module references
        terraform.append("\n# Module References\n")
        for module in submodules:
            if module != "main":
                terraform.append(f"""module "{module}" {{
  source = "./{module}"
}}
""")

        return "\n".join(terraform)
