"""
Document Generator for CARL Reports.

Converts markdown reports to professional Word documents and PDFs.
"""

import re
from io import BytesIO
from datetime import datetime
from typing import Optional

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

from utils.logger import get_logger

logger = get_logger(__name__)


class DocumentGenerator:
    """Generate professional Word documents from markdown reports."""

    def __init__(self):
        """Initialize the document generator."""
        pass

    def markdown_to_docx(self, markdown_content: str, title: str = "CARL Compliance Report") -> BytesIO:
        """
        Convert markdown content to a formatted Word document.

        Args:
            markdown_content: The markdown content to convert
            title: The document title

        Returns:
            BytesIO object containing the Word document
        """
        logger.info(f"Generating Word document: {title}")

        doc = Document()

        # Set up document properties
        core_properties = doc.core_properties
        core_properties.title = title
        core_properties.author = "CARL - Cloud Automated Risk & Compliance Logic"
        core_properties.created = datetime.utcnow()

        # Add title
        title_paragraph = doc.add_heading(title, 0)
        title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add generation timestamp
        timestamp = doc.add_paragraph()
        timestamp.add_run(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}").italic = True
        timestamp.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add blank line
        doc.add_paragraph()

        # Parse markdown and convert to document elements
        lines = markdown_content.split('\n')
        i = 0
        in_code_block = False
        code_lines = []

        while i < len(lines):
            line = lines[i]

            # Handle code blocks
            if line.strip().startswith('```'):
                if not in_code_block:
                    in_code_block = True
                    code_lines = []
                else:
                    # End of code block - add it to document
                    if code_lines:
                        code_para = doc.add_paragraph('\n'.join(code_lines))
                        code_para.style = 'Intense Quote'
                    in_code_block = False
                    code_lines = []
                i += 1
                continue

            if in_code_block:
                code_lines.append(line)
                i += 1
                continue

            # Handle headings
            if line.startswith('# '):
                doc.add_heading(line[2:], 1)
            elif line.startswith('## '):
                doc.add_heading(line[3:], 2)
            elif line.startswith('### '):
                doc.add_heading(line[4:], 3)
            elif line.startswith('#### '):
                doc.add_heading(line[5:], 4)

            # Handle horizontal rules
            elif line.strip() in ['---', '***', '___']:
                doc.add_paragraph('_' * 50)

            # Handle bullet lists
            elif line.strip().startswith('- ') or line.strip().startswith('* '):
                content = line.strip()[2:]
                doc.add_paragraph(content, style='List Bullet')

            # Handle numbered lists
            elif re.match(r'^\d+\.\s', line.strip()):
                content = re.sub(r'^\d+\.\s', '', line.strip())
                doc.add_paragraph(content, style='List Number')

            # Handle bold text emphasis
            elif '**' in line:
                para = doc.add_paragraph()
                parts = line.split('**')
                for idx, part in enumerate(parts):
                    if idx % 2 == 0:
                        para.add_run(part)
                    else:
                        para.add_run(part).bold = True

            # Handle blank lines
            elif not line.strip():
                doc.add_paragraph()

            # Regular paragraphs
            else:
                if line.strip():
                    # Clean up markdown formatting
                    clean_line = line.replace('_', '').replace('`', '')
                    doc.add_paragraph(clean_line)

            i += 1

        # Add footer with page numbers
        section = doc.sections[0]
        footer = section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = f"Generated by CARL | {datetime.utcnow().strftime('%Y-%m-%d')}"
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Save to BytesIO
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)

        logger.info("Word document generated successfully")
        return buffer

    def create_executive_summary_docx(
        self,
        markdown_content: str,
        organization_name: str = "Organization",
        audit_period: str = ""
    ) -> BytesIO:
        """
        Create a specially formatted executive summary Word document.

        Args:
            markdown_content: The markdown content
            organization_name: Organization name for the cover
            audit_period: Audit period for the cover

        Returns:
            BytesIO object containing the Word document
        """
        logger.info(f"Generating executive summary for {organization_name}")

        doc = Document()

        # Cover page
        cover_title = doc.add_heading('SOC 2 Type II', 0)
        cover_title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        cover_subtitle = doc.add_heading('Executive Summary', 1)
        cover_subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()
        doc.add_paragraph()

        org_para = doc.add_paragraph()
        org_run = org_para.add_run(organization_name)
        org_run.font.size = Pt(18)
        org_run.font.bold = True
        org_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        if audit_period:
            period_para = doc.add_paragraph()
            period_run = period_para.add_run(f"Audit Period: {audit_period}")
            period_run.font.size = Pt(14)
            period_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()

        generated_para = doc.add_paragraph()
        generated_run = generated_para.add_run(f"Generated: {datetime.utcnow().strftime('%B %d, %Y')}")
        generated_run.italic = True
        generated_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add page break
        doc.add_page_break()

        # Add the rest of the content using the standard markdown converter
        # Parse and add content (simplified for executive summary)
        lines = markdown_content.split('\n')
        for line in lines:
            if line.startswith('# '):
                doc.add_heading(line[2:], 1)
            elif line.startswith('## '):
                doc.add_heading(line[3:], 2)
            elif line.startswith('### '):
                doc.add_heading(line[4:], 3)
            elif line.strip().startswith('- '):
                doc.add_paragraph(line.strip()[2:], style='List Bullet')
            elif line.strip().startswith('**') and line.strip().endswith('**'):
                para = doc.add_paragraph()
                para.add_run(line.strip()[2:-2]).bold = True
            elif line.strip():
                doc.add_paragraph(line)

        # Save to BytesIO
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)

        logger.info("Executive summary document generated successfully")
        return buffer
